### ISSUE TITLE
Business idea image not compressed

### ISSUE THREAD

**Issue by finnhodgkin** [FAC-11/team-atoms#33]
`business-idea.png` is larger file than the banner image (534kb vs 249kb). When designing for mobile it's super important to keep file sizes low.

**Comment by absorpheus** [comment]
Used imageOptim to compress image from 534KB -> 318KB.

Any other tips to reduce the file size of images?

**Comment by finnhodgkin** [comment]
If the image is always going to be small you can shrink the image. `business-idea` is 730x430 pixels.

The largest it is ever displayed is 200 pixels wide.

:+1:
